# Сообщение, которое пишется при входе, если игрок не нажал на Shift. Есть поддержка локального плейсхолдера {TIME}. {TIME} - показывает игроку сколько осталось у него времени.
ShiftMessage: "&fПожалуйста, нажмите на Shift, или присядьте. У Вас осталось: &c{TIME}."
# Сообщение которое будет появляться после нажатия на Shift или приседания. Сообщение кликабельно. Также есть поддержка {TIME}.
Message: "&fНажмите на это сообщение. У Вас осталось: &c{TIME}."
# Если игрок не успел пройти капчу. Нету поддержки {TIME}.
KickMessage: "&cВы не успели пройти капчу!"
# Если игрок успешно прошел проверку. Нету поддержки {TIME}.
SuccessMessage: "&aПроверка пройдена, приятной игры!" 
# Если игрок попытался ввести команду /confirm и другой код.
WrongCodeMessage: "&cОшибка" 
# Сколько у игрока есть времени на проверку.
Delay: 30 
# Титлы. 
Titles:
  # Сообщение сверху самого титла при заходе игрока. Нет поддержки {TIME}. Текст больше, чем текст снизу титла. 
  StartTitle: "&cПРОВЕРКА"
  # Сообщение снизу начала титла. Есть поддержка {TIME}. Текст меньше, чем текст сверху.
  StartSubTitle: "&fНажмите на кнопку Shift, а затем на сообщение в чате!"
  # Сообщение сверху самого титла, когда игрок прошел проверку. Нет поддержки {TIME}. Текст больше, чем текст снизу титла. 
  SuccessTitle: "&aПРОВЕРКА"
  # Сообщение снизу начала титла. Есть поддержка {TIME}. Текст меньше, чем текст сверху.  
  SuccessSubTitle: "&fПроверка пройдена, приятной игры!"
BossBar:
  Enabled: true
  BossBarInfo: "&fЭто проверка, следуйте инструкции в чате. У вас есть &c{TIME}&f секунд."
  BossBarColor: RED
  BossBarStyle: SOLID  